services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: python src/main.py
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data   
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=password

  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
